### ISSUE TITLE
Add an option to specify nodeSelectors and Tolerations

### ISSUE THREAD

**Issue by bortek** [minio/direct-csi#235] opened 2021-05-18 14:15 UTC
Problem description

I have a cluster with bunch of regular compute nodes where the normal application pods are rubnnig. 
I also have a dedicated minio compute nodes which are for direct-csi minio pods. Thats where the disks are located that should be used by minio.

I use tolerations/labels on special minio nodes to block regular workloads from being scheduled. And also manually added nodeselector/tolerations on direct-csi daemonset and deploy to allow direct-csi pods been able to run on those special nodes. These is what I have in deploys/daemonsets

```yaml
    spec:
      containers:
      nodeSelector:
        node-role.kubernetes.io/minio: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/minio
        operator: Equal
```

Problem is if I install or upgrade direct-csi driver then everything is being reinstalled and my custom made adjustments to deploy and daemon sets will also be gone.

I need a way to be able to set tolerations and nodeselectors on deploy/damonset when running "kubectl direct-csi install" . Presumably with options like --tolerations="XXX,YYY,ZZZ or --tolerations="BASE64-STRING"  --nodeselector="YYY"

I guess many others would benefit from this too and many clusters have mixed node types.

**Comment by wlan0** [comment] 2021-05-18 19:06
Hi @bortek! 

This is definitely a good request. We will add this to the pipeline. Quick question: do you eed both node selectors and tolerations? Wouldn't just tolerations be enough?

**Comment by wlan0** [comment] 2021-05-18 19:06
Duplicate of https://github.com/minio/direct-csi/issues/105

**Comment by bortek** [comment] 2021-05-18 19:53
Thanks!

Not sure if only tolerations will be enough. Because there are different labels on different types of compute nodes we use those labels as nodeselectors.

**Closed** 2021-05-25 03:04 UTC
Labels: enhancement
