### ISSUE TITLE
kubectl direct-csi info

### ISSUE THREAD

**Issue by ljay88** [minio/direct-csi#358] opened 2021-08-28 02:47 UTC
kubectl direct-csi info

return

ERR: DirectCSI installation NOT found

run 'kubectl direct-csi install' to get started
ERROR DirectCSI installation not found

**Comment by ljay88** [comment] 2021-08-28 02:48
kubectl direct-csi drives ls

DRIVE  CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE  ACCESS-TIER  STATUS

Only the header, no content

**Comment by wlan0** [comment] 2021-08-28 04:34
@ljay88 
```
ERR: DirectCSI installation NOT found

run 'kubectl direct-csi install' to get started
ERROR DirectCSI installation not found
```

It seems like directCSI is not installed. As the message reads, did you run `kubectl direct-csi install`?

**Comment by ljay88** [comment] 2021-08-28 06:29
kubectl direct-csi install

return

I0828 02:28:48.156318 1469083 install.go:99] 'direct.csi.min.io' namespace created
W0828 02:28:48.181176 1469083 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
I0828 02:28:48.188699 1469083 install.go:119] 'direct.csi.min.io' rbac roles created
I0828 02:28:48.232605 1469083 install.go:137] crds successfully registered
I0828 02:28:48.255582 1469083 install.go:146] 'direct.csi.min.io' conversion deployment created
I0828 02:28:48.296228 1469083 register.go:124] successfully updated conversion webhook settings in 'directcsidrives.direct.csi.min.io' CRD
I0828 02:28:48.316345 1469083 register.go:124] successfully updated conversion webhook settings in 'directcsivolumes.direct.csi.min.io' CRD
I0828 02:28:49.357215 1469083 request.go:668] Waited for 1.037061576s due to client-side throttling, not priority and fairness, request: GET:https://192.168.3.55:6443/apis/discovery.k8s.io/v1?timeout=32s
I0828 02:28:49.662246 1469083 install.go:159] 'direct.csi.min.io' csidriver created
I0828 02:28:51.513194 1469083 install.go:168] 'direct.csi.min.io' storageclass created
I0828 02:28:51.545340 1469083 install.go:177] 'direct.csi.min.io' service created
I0828 02:28:51.571787 1469083 install.go:186] 'direct.csi.min.io' daemonset created
I0828 02:28:55.832034 1469083 install.go:195] 'direct.csi.min.io' deployment created

**Comment by ljay88** [comment] 2021-08-28 06:31
The execution is still the same as above

**Comment by ljay88** [comment] 2021-08-28 06:36
DirectCSI has been installed, but the total number of kubectl direct-csi info shows that it is not installed
still have a question
Executing kubectl direct-csi drives ls always returns no content in the header

**Comment by wlan0** [comment] 2021-08-28 07:08
I see. Could you please paste the version of directCSI and kubernetes as well.

```
$ kubectl version 
$ kubectl direct-csi version
```

**Comment by ljay88** [comment] 2021-08-28 07:09
#kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

#kubectl direct-csi version

Error: unknown command "version" for "direct-csi"
Run 'direct-csi --help' for usage.
ERROR unknown command "version" for "direct-csi"

**Comment by ljay88** [comment] 2021-08-28 07:11
# kubectl direct-csi --version

direct-csi version v1.4.2

**Comment by wlan0** [comment] 2021-08-29 00:45
Thanks @ljay88, I'll reproduce it and get back to you

**Comment by Praveenrajmani** [comment] 2021-08-29 05:38
can you check if there are any errors in the direct-csi pods? - `kubectl get pods -n direct-csi-min-io`

**Comment by ljay88** [comment] 2021-08-30 00:59
kubectl get pods -n direct-csi-min-io
NAME                                            READY   STATUS    RESTARTS   AGE
direct-csi-min-io-5ddd458cf4-dng6h              2/2     Running   0          82s
direct-csi-min-io-5ddd458cf4-jksfx              2/2     Running   0          82s
direct-csi-min-io-5ddd458cf4-lb7rz              2/2     Running   0          82s
direct-csi-min-io-5wc7f                         3/3     Running   0          92s
direct-csi-min-io-dzprc                         3/3     Running   0          92s
direct-csi-min-io-vl7mh                         3/3     Running   0          92s
directcsi-conversion-webhook-775c7b469c-dkvdt   1/1     Running   0          118s
directcsi-conversion-webhook-775c7b469c-g7mpv   1/1     Running   0          118s
directcsi-conversion-webhook-775c7b469c-q6776   1/1     Running   0          118s

**Comment by Praveenrajmani** [comment] 2021-08-30 03:12
Looks like the drive discovery on the nodes you have weren't successful. We need the output of the following commands

```
kubectl get directcsidrives -o yaml
kubectl logs direct-csi-min-io-5wc7f -n direct-csi-min-io direct-csi

lsblk -a (from any of the  nodes)
```

You can redirect them to separate files and attach them here.

**Comment by Praveenrajmani** [comment] 2021-08-30 03:13
@ljay88 ^^

**Comment by ljay88** [comment] 2021-08-30 03:20
kubectl get directcsidrives -o yaml
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

logs direct-csi-min-io-5wc7f -n direct-csi-min-io direct-csi
I0830 03:19:15.964635   15849 init.go:86] obtained client config successfully

lsblk -a
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda           8:0    0   30G  0 disk
├─sda1        8:1    0  600M  0 part /boot/efi
├─sda2        8:2    0    1G  0 part /boot
└─sda3        8:3    0 28.4G  0 part
  ├─cl-root 253:0    0 25.4G  0 lvm  /
  └─cl-swap 253:1    0    3G  0 lvm
sr0          11:0    1 1024M  0 rom

**Comment by Praveenrajmani** [comment] 2021-08-30 03:30
```

@ljay88 Can you also paste me the `kubectl get crds` command?

**Comment by Praveenrajmani** [comment] 2021-08-30 03:32
> I0830 03:19:15.964635 15849 init.go:86] obtained client config successfully
Do you see any other log lines from this pod @ljay88 ?

Can you also get the output of `kubectl get crds`?

**Comment by ljay88** [comment] 2021-08-30 03:34
Did not see any logs.

**Comment by ljay88** [comment] 2021-08-30 03:34
kubectl get crds
NAME                                 CREATED AT
directcsidrives.direct.csi.min.io    2021-08-30T00:56:34Z
directcsivolumes.direct.csi.min.io   2021-08-30T00:56:34Z

**Comment by Praveenrajmani** [comment] 2021-08-30 03:37
@ljay88 Can you enable the verbosity level in the direct-csi daemonset? you can do that by `kubectl edit daemonset direct-csi-min-io -n direct-csi-min-io` and change `-v=3` to `-v=10` under `direct-csi` container

**Comment by ljay88** [comment] 2021-08-30 03:41
Let me try

**Comment by ljay88** [comment] 2021-08-30 03:53
kubectl get pods -n direct-csi-min-io
NAME                                            READY   STATUS    RESTARTS       AGE
direct-csi-min-io-5ddd458cf4-dng6h              2/2     Running   2 (166m ago)   175m
direct-csi-min-io-5ddd458cf4-jksfx              2/2     Running   3 (33m ago)    175m
direct-csi-min-io-5ddd458cf4-lb7rz              2/2     Running   2 (166m ago)   175m
direct-csi-min-io-7lvs5                         3/3     Running   1 (117s ago)   7m23s
direct-csi-min-io-7npkg                         3/3     Running   1 (114s ago)   7m20s
direct-csi-min-io-bqfd4                         3/3     Running   1 (110s ago)   7m16s
directcsi-conversion-webhook-775c7b469c-dkvdt   1/1     Running   1 (166m ago)   175m
directcsi-conversion-webhook-775c7b469c-g7mpv   1/1     Running   1 (166m ago)   175m
directcsi-conversion-webhook-775c7b469c-q6776   1/1     Running   1 (166m ago)   175m

kubectl logs direct-csi-min-io-7lvs5
Error from server (NotFound): pods "direct-csi-min-io-7lvs5" not found

**Comment by ljay88** [comment] 2021-08-30 03:54
kubectl logs direct-csi-min-io-7lvs5 -n direct-csi-min-io
error: a container name must be specified for pod direct-csi-min-io-7lvs5, choose one of: [node-driver-registrar direct-csi liveness-probe]

**Comment by Praveenrajmani** [comment] 2021-08-30 03:55
`kubectl logs direct-csi-min-io-7lvs5 -n direct-csi-min-io direct-csi` is the command

**Comment by ljay88** [comment] 2021-08-30 03:55
kubectl logs direct-csi-min-io-7lvs5 -n direct-csi-min-io direct-csi
I0830 03:50:34.439801   28216 init.go:86] obtained client config successfully
I0830 03:51:24.449841   28216 run.go:79] Waiting for conversion webhook: Get "https://directcsi-conversion-webhook.direct-csi-min-io.svc/healthz": dial tcp: lookup directcsi-conversion-webhook.direct-csi-min-io.svc on 10.10.0.10:53: read udp 10.244.1.8:36639->10.10.0.10:53: i/o timeout
I0830 03:52:17.465124   28216 run.go:79] Waiting for conversion webhook: Get "https://directcsi-conversion-webhook.direct-csi-min-io.svc/healthz": dial tcp: lookup directcsi-conversion-webhook.direct-csi-min-io.svc on 10.10.0.10:53: read udp 10.244.1.8:34292->10.10.0.10:53: i/o timeout
I0830 03:53:10.469949   28216 run.go:79] Waiting for conversion webhook: Get "https://directcsi-conversion-webhook.direct-csi-min-io.svc/healthz": dial tcp: lookup directcsi-conversion-webhook.direct-csi-min-io.svc on 10.10.0.10:53: read udp 10.244.1.8:37793->10.10.0.10:53: i/o timeout
I0830 03:54:03.487449   28216 run.go:79] Waiting for conversion webhook: Get "https://directcsi-conversion-webhook.direct-csi-min-io.svc/healthz": dial tcp: lookup directcsi-conversion-webhook.direct-csi-min-io.svc on 10.10.0.10:53: read udp 10.244.1.8:40448->10.10.0.10:53: i/o timeout
I0830 03:54:56.497447   28216 run.go:79] Waiting for conversion webhook: Get "https://directcsi-conversion-webhook.direct-csi-min-io.svc/healthz": dial tcp: lookup directcsi-conversion-webhook.direct-csi-min-io.svc on 10.10.0.10:53: read udp 10.244.1.8:52520->10.10.0.10:53: i/o timeout

**Comment by Praveenrajmani** [comment] 2021-08-30 04:02
> read udp 10.244.1.8:52520->10.10.0.10:53: i/o timeout

Looks like your CoreDNS is overloaded @ljay88 you have to fix them. It should be running in `kube-system` namespace.

**Comment by ljay88** [comment] 2021-08-30 04:03
Thanks, i'll try

**Comment by Praveenrajmani** [comment] 2021-08-30 04:04
Closing this issue for now, please feel free to re-open if you have any other issues/questions. @ljay88

**Closed by Praveenrajmani** 2021-08-30 04:04 UTC

**Comment by elissonrusiel** [comment] 2022-05-09 20:33
Hello, 
I'm facing the same error when an execute the info command. I've followed the recommended steps I can list and format the drives, but still getting the error on `kubectl directpv info` and the automatic provisioning doesn't work.
What can be the reason of the error and the automatic provisioning malfunctioning? Any help is welcome.

```
$ kubectl directpv info
ERR: directpv installation NOT found

run 'kubectl directpv install' to get started
ERROR directpv installation not found
```
### Environment versions:
#### microk8s stable 1.21
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-21T03:44:32Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-3+6937f71915b56b", GitCommit:"6937f71915b56b6004162b7c7b3f11f196100d44", GitTreeState:"clean", BuildDate:"2022-04-28T11:11:24Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
#### Krew
```
kubectl krew list
PLUGIN    VERSION
directpv  v3.0.0
krew      v0.4.3
minio     v4.4.17
```
### Commands outputs

```
kubectl directpv install
W0509 22:14:40.562295 1162566 installer.go:76] running on experimental version of kubernetes v1.21+. This version is not officially supported yet.
I0509 22:14:40.575293 1162566 ns.go:55] 'direct.csi.min.io' namespace created
I0509 22:14:40.588466 1162566 rbac.go:352] 'direct.csi.min.io' rbac created
W0509 22:14:40.600054 1162566 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
I0509 22:14:40.604095 1162566 psp.go:129] 'direct.csi.min.io' podsecuritypolicy created
I0509 22:14:40.609087 1162566 conversion_secret.go:170] 'direct.csi.min.io' conversion webhook secrets created
I0509 22:14:40.687285 1162566 crd.go:135] crds successfully registered
I0509 22:14:40.758651 1162566 csidriver.go:150] 'direct.csi.min.io' csidriver created
I0509 22:14:41.870117 1162566 storageclass.go:50] 'direct.csi.min.io' storageclass created
I0509 22:14:41.901319 1162566 service.go:39] 'direct.csi.min.io' service created
I0509 22:14:41.916725 1162566 daemonset.go:41] 'direct.csi.min.io' daemonset created
I0509 22:14:41.948554 1162566 deployment.go:295] 'direct.csi.min.io' deployment created
```

```
kubectl directpv drives ls
 DRIVE           CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE   ACCESS-TIER  STATUS      
 /dev/nvme0n1p1  128 MiB   -          -           -        emaia  -            Available   
 /dev/nvme0n1p3  249 GiB   -          ntfs        -        emaia  -            Available   
 /dev/nvme0n1p5  123 MiB   -          ext4        -        emaia  -            Available   
 /dev/nvme0n1p6  30 GiB    -          xfs         -        emaia  -            Ready
```

```
kubectl get pods -n direct-csi-min-io
NAME                                 READY   STATUS    RESTARTS   AGE
direct-csi-min-io-66d7d8c9f8-qgc2g   2/2     Running   0          54m
direct-csi-min-io-66d7d8c9f8-6d72w   2/2     Running   0          54m
direct-csi-min-io-66d7d8c9f8-268rj   2/2     Running   0          54m
direct-csi-min-io-k9hbp              4/4     Running   0          17m
```

```
kubectl get crds
NAME                                          CREATED AT
bgpconfigurations.crd.projectcalico.org       2022-05-09T19:17:13Z
blockaffinities.crd.projectcalico.org         2022-05-09T19:17:13Z
bgppeers.crd.projectcalico.org                2022-05-09T19:17:13Z
clusterinformations.crd.projectcalico.org     2022-05-09T19:17:13Z
felixconfigurations.crd.projectcalico.org     2022-05-09T19:17:13Z
globalnetworkpolicies.crd.projectcalico.org   2022-05-09T19:17:13Z
globalnetworksets.crd.projectcalico.org       2022-05-09T19:17:13Z
hostendpoints.crd.projectcalico.org           2022-05-09T19:17:13Z
ipamblocks.crd.projectcalico.org              2022-05-09T19:17:13Z
ipamconfigs.crd.projectcalico.org             2022-05-09T19:17:13Z
ipamhandles.crd.projectcalico.org             2022-05-09T19:17:13Z
ippools.crd.projectcalico.org                 2022-05-09T19:17:13Z
networkpolicies.crd.projectcalico.org         2022-05-09T19:17:13Z
networksets.crd.projectcalico.org             2022-05-09T19:17:13Z
httpapispecs.config.istio.io                  2022-05-09T19:23:58Z
httpapispecbindings.config.istio.io           2022-05-09T19:23:58Z
quotaspecs.config.istio.io                    2022-05-09T19:23:58Z
quotaspecbindings.config.istio.io             2022-05-09T19:23:58Z
meshpolicies.authentication.istio.io          2022-05-09T19:23:58Z
policies.authentication.istio.io              2022-05-09T19:23:58Z
envoyfilters.networking.istio.io              2022-05-09T19:23:58Z
gateways.networking.istio.io                  2022-05-09T19:23:58Z
serviceentries.networking.istio.io            2022-05-09T19:23:58Z
sidecars.networking.istio.io                  2022-05-09T19:23:58Z
virtualservices.networking.istio.io           2022-05-09T19:23:58Z
attributemanifests.config.istio.io            2022-05-09T19:23:58Z
handlers.config.istio.io                      2022-05-09T19:23:58Z
instances.config.istio.io                     2022-05-09T19:23:58Z
rules.config.istio.io                         2022-05-09T19:23:58Z
clusterrbacconfigs.rbac.istio.io              2022-05-09T19:23:58Z
rbacconfigs.rbac.istio.io                     2022-05-09T19:23:58Z
serviceroles.rbac.istio.io                    2022-05-09T19:23:58Z
servicerolebindings.rbac.istio.io             2022-05-09T19:23:58Z
authorizationpolicies.security.istio.io       2022-05-09T19:23:58Z
peerauthentications.security.istio.io         2022-05-09T19:23:58Z
destinationrules.networking.istio.io          2022-05-09T19:23:58Z
requestauthentications.security.istio.io      2022-05-09T19:23:58Z
clusterissuers.certmanager.k8s.io             2022-05-09T19:23:58Z
issuers.certmanager.k8s.io                    2022-05-09T19:23:58Z
certificates.certmanager.k8s.io               2022-05-09T19:23:58Z
orders.certmanager.k8s.io                     2022-05-09T19:23:59Z
challenges.certmanager.k8s.io                 2022-05-09T19:23:59Z
adapters.config.istio.io                      2022-05-09T19:23:59Z
templates.config.istio.io                     2022-05-09T19:23:59Z
directcsidrives.direct.csi.min.io             2022-05-09T19:28:24Z
directcsivolumes.direct.csi.min.io            2022-05-09T19:28:25Z

```

```
kubectl logs direct-csi-min-io-k9hbp -n direct-csi-min-io direct-csi
I0509 20:05:15.704224 1135485 init.go:108] obtained client config successfully
I0509 20:05:15.774753 1135485 webhook.go:72] Starting conversion webhook server in port: 30443
I0509 20:05:15.786853 1135485 run.go:169] The conversion webhook is live!
I0509 20:05:15.786863 1135485 run.go:175] identity server started
I0509 20:05:15.902496 1135485 run.go:183] enabled reflink while formatting
I0509 20:05:15.903059 1135485 leaderelection.go:243] attempting to acquire leader lease direct-csi-min-io/emaia-volume-controller...
I0509 20:05:15.903144 1135485 leaderelection.go:243] attempting to acquire leader lease direct-csi-min-io/emaia-drive-controller...
I0509 20:05:15.903162 1135485 run.go:222] node server started
I0509 20:05:15.903366 1135485 metrics.go:41] Starting metrics exporter in port: 10443
I0509 20:05:15.915745 1135485 leaderelection.go:253] successfully acquired lease direct-csi-min-io/emaia-drive-controller
I0509 20:05:15.915812 1135485 listener.go:383] new leader detected, current leader: emaia
I0509 20:05:15.915873 1135485 listener.go:376] became leader, starting
I0509 20:05:15.915927 1135485 listener.go:315] Starting drive controller
I0509 20:05:15.915981 1135485 reflector.go:219] Starting reflector *v1beta4.DirectCSIDrive (1m0s) from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I0509 20:05:15.915992 1135485 reflector.go:255] Listing and watching *v1beta4.DirectCSIDrive from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I0509 20:05:15.918774 1135485 leaderelection.go:253] successfully acquired lease direct-csi-min-io/emaia-volume-controller
I0509 20:05:15.918810 1135485 listener.go:383] new leader detected, current leader: emaia
I0509 20:05:15.918886 1135485 listener.go:376] became leader, starting
I0509 20:05:15.918932 1135485 listener.go:315] Starting volume controller
I0509 20:05:15.918976 1135485 reflector.go:219] Starting reflector *v1beta4.DirectCSIVolume (1m0s) from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I0509 20:05:15.918984 1135485 reflector.go:255] Listing and watching *v1beta4.DirectCSIVolume from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
```

```
lsblk -a
nvme0n1     259:0    0   477G  0 disk 
|-nvme0n1p1 259:1    0   128M  0 part 
|-nvme0n1p2 259:2    0   100M  0 part /boot/efi
|-nvme0n1p3 259:3    0 248.8G  0 part 
|-nvme0n1p4 259:4    0 197.9G  0 part /
|-nvme0n1p5 259:5    0   123M  0 part 
`-nvme0n1p6 259:6    0  29.9G  0 part /var/lib/direct-csi/mnt/5f66fed7-fd5a-b33a-e059-d175b14c179b
```
